language: node_js
node_js:
  - 14
services:
  - docker

install:
  - echo "no test"

script:
  - docker --version
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # tagging
  - docker tag udagram-api-user baobao4124/udagram-api-user:v1
  - docker tag udagram-api-feed baobao4124/udagram-api-feed:v1
  - docker tag udagram-frontend baobao4124/udagram-frontend:v1
  - docker tag udagram-reverseproxy baobao4124/udagram-reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push baobao4124/udagram-api-user:v1
  - docker push baobao4124/udagram-api-feed:v1
  - docker push baobao4124/udagram-frontend:v1
  - docker push baobao4124/udagram-reverseproxy:v1